/**
 * Hotel Service
 *
 * Business logic layer for hotel operations.
 * Contains functions for checking availability and making reservations.
 *
 * In a production application, these functions would interact with
 * a database instead of using mock data.
 */

import { HOTELS } from "../config/hotels.data.js";
import type { AvailableHotel, Reservation } from "../types/index.js";

const round6 = (n: number): number => {
  return Math.round(n * 1e6) / 1e6;
};

/**
 * Check hotel availability for given dates and guest count
 *
 * @param checkIn - Check-in date (YYYY-MM-DD)
 * @param checkOut - Check-out date (YYYY-MM-DD)
 * @param guests - Total number of guests
 * @returns Array of available hotels with booking details
 *
 * @example
 * const hotels = checkAvailability("2024-01-15", "2024-01-20", 2);
 */
export const checkAvailability = (
  checkIn: string,
  checkOut: string,
  destination: string,
  guests: number
): AvailableHotel[] => {
  // In a real application, we would query a database using these parameters
  // to find hotels that have availability for the requested dates and capacity.
  // For this mock implementation, we return all hotels with the requested dates.
  const nights =
    Math.ceil(
      (new Date(checkOut).getTime() - new Date(checkIn).getTime()) /
        (1000 * 60 * 60 * 24)
    ) || 1;

  const lowerCaseDestination = destination.toLowerCase();

  return HOTELS.filter(hotel =>
    hotel.location.toLowerCase().includes(lowerCaseDestination)
  ).map((hotel): AvailableHotel => ({
    hotelName: hotel.hotelName,
    location: hotel.location,
    roomType: hotel.roomType,
    price: round6(hotel.price * nights),
    imageUrl: hotel.imageUrl,
    dates: `${checkIn} to ${checkOut}`,
    guests,
  }));
};

/**
 * Reserve a hotel room
 *
 * Creates a reservation for the specified hotel and dates.
 * Calculates the total price based on number of nights.
 *
 * @param hotelName - Name of the hotel to reserve
 * @param checkIn - Check-in date (YYYY-MM-DD)
 * @param checkOut - Check-out date (YYYY-MM-DD)
 * @param guests - Total number of guests
 * @returns Reservation confirmation object
 * @throws Error if hotel is not found
 *
 * @example
 * const reservation = reserveHotel(
 *   "Grand Plaza Hotel",
 *   "2024-01-15",
 *   "2024-01-20",
 *   2
 * );
 */
export const reserveHotel = (
  hotelName: string,
  checkIn: string,
  checkOut: string,
  guests: number
): Reservation => {
  // Find the hotel in the database
  const hotel = HOTELS.find((h) => h.hotelName === hotelName);

  if (!hotel) {
    throw new Error(`Hotel "${hotelName}" not found`);
  }

  // Calculate number of nights
  const checkInDate = new Date(checkIn);
  const checkOutDate = new Date(checkOut);
  const nights =
    Math.ceil(
      (checkOutDate.getTime() - checkInDate.getTime()) / (1000 * 60 * 60 * 24)
    ) || 1;

  // Calculate total price (price per night * number of nights)
  const totalPrice = hotel.price * nights;

  // Generate a unique reservation ID
  // In production, this would be generated by the database
  const reservationId = `RES-${Date.now()}-${Math.random()
    .toString(36)
    .substring(2, 11)
    .toUpperCase()}`;

  // Return reservation confirmation
  return {
    reservationId,
    hotelName: hotel.hotelName,
    location: hotel.location,
    roomType: hotel.roomType,
    checkIn,
    checkOut,
    nights,
    guests,
    totalPrice,
    status: "confirmed",
    imageUrl: hotel.imageUrl,
  };
};
